services:
  - type: web
    name: thesis-tracker-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    plan: free
    envVars:
      - key: PYTHONPATH
        value: /app
      - key: DATABASE_URL
        value: postgresql://ekram1181:K1pqGBK3cYmrLn0lGIkeaNHOK1eyxRM1@dpg-ctskevi3esus73dr9ftg-a/mttopicfau
    healthCheckPath: /health

  - type: web
    name: thesis-tracker-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    plan: free
    buildCommand: npm install && npm run build
    autoDeploy: true
